# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sal Munoz's Code Blog
email: munoz.sal3@gmail.com
description: > # 
  Former community organizer turned coder. This is where I will track my 
  progress as I further build my skills and portfolio. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://mexistentialist.github.io/" # the base hostname & protocol for your site
twitter_username: Munoz_Sal3
github_username:  mexistentialist

# Build settings
markdown: kramdown
